### ISSUE TITLE
Alignment issues with wizard on RCUE 3.23 (does not affect PatternFly 3.23)

### ISSUE THREAD

**Issue by jawnsy** [redhat-rcue/rcue#69]
Hi,

There seems to be a strange alignment problem with the wizard steps indicator. Inexplicably, it only affects RCUE 3.23 and does not affect PatternFly 3.23.

PatternFly 3.23 - http://codepen.io/anon/pen/ryqzpj

![screenshot from 2017-03-28 14-03-48](https://cloud.githubusercontent.com/assets/52710/24427352/829c5ee4-13bf-11e7-9af3-9903d3ac14bb.png)

RCUE 3.23 - http://codepen.io/anon/pen/MpPvOe

![screenshot from 2017-03-28 14-03-51](https://cloud.githubusercontent.com/assets/52710/24427357/8729d040-13bf-11e7-88d8-d35a387104c4.png)

**Comment by jawnsy** [comment]
@andresgalante suggested checking the latest RCUE (3.23.1) and unfortunately the problem still exists there too. I need to get some other stuff merged first but will do some more investigation next week.

![screenshot from 2017-03-30 15-25-41](https://cloud.githubusercontent.com/assets/52710/24528882/71f4512e-155d-11e7-8871-a705a7a739dd.png)

Updated codepen: http://codepen.io/jawnsy/pen/BWvjzx

I've confirmed that `patternfly.version` from the console reports 3.23.1

**Comment by andresgalante** [comment]
Thanks for reporting this, I could reproduce the bug. I'll look into it.

**Comment by andresgalante** [comment]
The issue is on `wizard-pf-step-number`. It should be `left: calc(50% - 13px)` instead of `37px`.

**Comment by andresgalante** [comment]
**Solution:** Escape `calc` so less doesn't compile it. `~"calc(50% - 13px)";` 

@jawnsy  I'll fix this on patternfly, when do you need it on RCUE? can it wait till next release in 2 weeks?

@srambach please check this one out, for next time we do calc :)

**Comment by jawnsy** [comment]
Thanks for the quick fix! There's no urgency on our end, we can wait until the next release; we'll just stay on PatternFly in the meantime.
