### ISSUE TITLE
Missing 'bg-modal-about-pf.png' referenced in rcue-additions, rcue.css, variables.less

### ISSUE THREAD

**Issue by akoserwal** [redhat-rcue/rcue#81]
"bg-modal-about-pf.png" is referenced at 7 files but I can't find in "/dist/img/" 

- rcue-additions.css, rcue-additions.css.map, rcue-additions.min.css
` background-image: url("../img/bg-modal-about-pf.png");`
- rcue.css.map	
- styles-additions.css, style-additions.min.css
` background-image: url("../img/bg-modal-about-pf.png");`
- variables.less
`@modal-about-pf-bg-img:                             "bg-modal-about-pf.png";`

**Comment by sjd78** [comment]
I ran into the same problem.  The build script that copies static assets forward from the source patternfly assets skips the images.  I have a small fix to the script and will submit a PR soon.

**Comment by jeff-phillips-18** [comment]
Fixed in 3.37.1
